# Config file for [Air](https://github.com/air-verse/air) in TOML format

root = "."
tmp_dir = "tmp"

[build]
  # Build command
  cmd = "go build -o ./tmp/main ."
  # Binary file
  bin = "./tmp/main"
  full_bin = "./tmp/main"
  # Extension to watch
  include_ext = ["go", "tpl", "tmpl", "html", "env"]
  # Directories to ignore
  exclude_dir = ["assets", "tmp", "vendor", "test"]
  # Files to ignore
  exclude_file = []
  # Delay after editing (ms)
  delay = 1000
  # Stop running old binary when build errors occur.
  stop_on_error = true
  # Send Interrupt signal before killing process
  send_interrupt = false
  # Delay after sending Interrupt signal
  kill_delay = 500 # ms

[log]
  # Show log time
  time = true

[color]
  # Customize each part's color.
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  # Delete tmp directory on exit
  clean_on_exit = true
